### PR TITLE
Avoid duplicated categories in table filter when clicking "check all"

### PR DESCRIPTION
**Pull request by bobular**
See https://github.com/VEuPathDB/web-eda/issues/28

### CODE REVIEW

**Review by dmfalke — APPROVED** [review]

**Comment by dmfalke** [comment]
I will need to publish a new version of this package. It hasn’t been
automated here yet.

**Comment by bobular** [comment]
> I will need to publish a new version of this package. It hasn’t been automated here yet.
> […](#)

I did some tagging/releasing through github - but maybe that's not enough?

**Comment by dmfalke** [comment]
No, it has to be done with the npm or yarn cli command.

**Comment by bobular** [comment]
Hope I didn't make it more complicated for you...

**Pull request merged**
