### PR TITLE
FilterParamNew: add paging to large membership fields

### PR DESCRIPTION
**Pull request by wbazant**
Can be tested on https://wbazant.microbiomedb.org/mbio.wbazant/app/search/sample/SamplesByMetadata_otuDADA2_MALED_healthy_RSRC with an apidb password - some sample details like "SRA Experiment ID" are alternative IDs, and there's over a thousand rows. I acknowledge there's little very point for MicrobiomeDB to show this study while offer those filters, but it's there, and can be used as a test case.

Main rationale of this feature is to make improperly large membership fields usable. This came up for user datasets in MicrobiomeDB and an example input from Earth Microbiome Project, containing thousands of unannotated samples. The UI broke down on this case because rendering of all rows took too long.

Only page if there are over 100 values: there shouldn't usually be this many.

Offer page sizes of 50, 100, 200, and 1000. Changing pages tries to preserve values that are being shown.

When a search term is entered:
- set lower opacity for a grey out effect
- set pointer events to none
- use page size as maximum search count

Add an "indeterminate" state of a Select All checkbox, when some elements are selected. Clicking "Select All" on paged rows selects the current page (similar to behaviour with a search term).
One consequence is that it's not possible to unclick a page. I tried to make it work but it was difficult to get something non-broken, so went for consistency in the end.

Fix a small bug in MesaController.jsx, renderPaginationMenu: the parameter `rowsPerPageOptions` wasn't passed along.

MembershipField.jsx small refactor: make `getRows()` a method similarly named to `getFilteredRows()`.

### CODE REVIEW

**Comment by wbazant** [comment]
@dmfalke You're right about the problem of current page showing up during search, it is inconsistent.

I started out with by applying first pagination, then filtering, which results in the filtering only applied to the current page, which makes it less useful. If it happens the other way round, then the number of pages changes as you type.

What do you think about strengthening the visual cue about the bar being inactive, by removing the current page element being greyed in? I've failed, like, ten times to write working CSS which would only show the buttons as "active/inactive" when the elements are clickable, it would look something like
Screenshot from 2020-07-06 14-23-27. I guess I could do it in JSX or learn CSS more.

I value the UX meeting as a meeting which centralizes box ticking, but I'm not sure if it would help. It has a big attendance, but. each person there only spends a small amount of time on each problem presented to the meeting, which limits how useful their suggestions can be. Maybe asking one more person to join this review, and having them spend say twenty minutes on it, could be more productive.

**Comment by wbazant** [comment]
A more radical visual cue - remove the bar and leave the space and a crossed-out "rows per page" menu to show that the bar is temporarily gone:
Screenshot from 2020-07-06 14-38-15

**Comment by dmfalke** [comment]
I think it's ok that the number of pages changes as the user types. I guess I would have to see it in action, though. I would prefer this to not being able to page through the filtered rows.

Regarding UX, whatever ends up on the site will ultimately need to be reviewed by the group. If you want feedback on a specific issue, it's helpful to post a message in the slack channel (you can even link to this PR).

**Comment by wbazant** [comment]
Having the search filter results drive the pagination is worth trying, it's a bigger lift code-wise (filtering the rows needs to move out of `MembershipTable` ) but I'll have a go.

**Comment by dmfalke** [comment]
I don’t think so. You just have to reset pagination when the filter term
changes. Then, first filter the rows, then slice out the rows based on
pagination details.

**Comment by wbazant** [comment]
@dmfalke I've implemented filtering before pagination, with current page resetting when search term changes. Can you try it out?

**Comment by dmfalke** [comment]
This looks good!

**Pull request merged**
